### ISSUE TITLE
Calibration: Calibration Menu hangs when no Myo connected

### ISSUE THREAD

**Issue by aarontabor** [hcilab/processing-games#1] opened 2016-05-17 16:15 UTC
When the "MyoConnect" software is open, but no Myo is connected, the calibration menu hangs and the program becomes unresponsive.

I assume that this is because the "Bluetooth Connect" request is waiting to time out before calibration fails, but I need to investigate further to confirm.

**Comment by ThePenguin1140** [comment] 2016-05-20 15:06
Seems to be duplicate of #3

**Closed** 2016-05-24 13:50 UTC
Labels: duplicate
