### ISSUE TITLE
Button appearance is inconsistent across game states

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#23] opened 2016-05-20 18:31 UTC
Buttons have different appearances in different screens. This includes a lack of icon for the back button or the lack of a button sprite for green GUI buttons.

- [x] The calibration screen does not have sprites for it's buttons yet #22 
- [ ] The **Stats Collected** screen still needs to have it's back button fixed.

**Comment by AlexKienzle** [comment] 2016-05-24 12:02
This issue has been resolved, but the green button on the calibration menu is still outdated (generic green rectangle). This issue also persists on the "Score Collected" screen (the back button and the green buttons are outdated).

**Comment by ThePenguin1140** [comment] 2016-05-24 12:40
Which screens does the back button still need to be fixed?
This issue is for the back buttons only, #12 is for the green buttons

**Comment by AlexKienzle** [comment] 2016-05-24 12:58
I believe the only remaining back button that needs to be fixed is on the "Score Collected" screen.

**Comment by AlexKienzle** [comment] 2016-05-24 12:59
Also, I thought #12 was concerned with the green buttons only working when you click the text, not the addition of sprites.

**Comment by ThePenguin1140** [comment] 2016-05-24 13:03
Oh yea, you're right. Alright I made this issue more general to encompass both buttons

**Comment by AlexKienzle** [comment] 2016-05-26 12:24
All buttons appear to have the appropriate sprites now, and all red ellipses are finally gone. The buttons all function as intended too. Closing.

**Closed by AlexKienzle** 2016-05-26 12:24 UTC
Labels: !minor, #cosmetic, %settings, &review, Fall of Momo
